# EdgeTX Lua tool LCD resolution (path=WxH)
# Set from Radio -> Tools: long-press a Lua tool
SCRIPTS/TOOLS/FPV simulator.lua=480x320
SCRIPTS/TOOLS/LuaAbs480x320.lua=480x320
SCRIPTS/TOOLS/NavHUD.lua=480x320
SCRIPTS/TOOLS/Xuan-HUD.lua=480x320
